// Finds explicit legal references ("Section 489-F PPC", "Article 10A", "دفعہ ۳۰۲") in text.
// Used to fetch the exact provisions a user names, and to check citations in AI answers.

import catalogJson from "./catalog.json";
import { LAWS, type LawId } from "./laws";

// law -> provision number -> { title, chunk ids }. Generated by scripts/rag/build-knowledge.mjs.
export type Catalog = Record<string, Record<string, { title: string; ids: string[] }>>;
export const catalog = catalogJson as Catalog;

export interface LegalReference {
  law: LawId;
  number: string;
  // false when the text names a provision that is not in the knowledge base (possibly invented).
  known: boolean;
}

// One place in the text that cites a provision. When the law is not named ("Section 54"),
// it may refer to more than one law, so it lists every possibility.
export interface ReferenceMention {
  text: string;
  options: LegalReference[];
}

const URDU_DIGITS = /[۰-۹٠-٩]/g;
// Urdu digits -> 0-9, and hyphen look-alikes ("489‑F" with U+2011) -> "-".
function normalize(text: string): string {
  return text
    .replace(URDU_DIGITS, (d) => {
      const code = d.charCodeAt(0);
      return String(code >= 0x06f0 ? code - 0x06f0 : code - 0x0660);
    })
    .replace(/[‐-―−]/g, "-");
}

// "489", "489F", "489-F", "489 F", "10A"
const NUMBER = String.raw`(?<!\d)(\d{1,3})(?!\d)(?:\s?-\s?([A-Za-z]{1,3})\b|([A-Za-z]{1,3})\b|\s([A-Z])\b)?`;
const UNIT_FIRST = new RegExp(
  String.raw`(?<![A-Za-z])(sections?|sec\.|s\.|articles?|art\.|دفعہ|دفعات|سیکشن|آرٹیکل|شق)\s*(?:no\.?\s*)?${NUMBER}`,
  "gi",
);
const LAW_AFTER_NUMBER = new RegExp(
  String.raw`${NUMBER}\s*(?:of\s+(?:the\s+)?)?(ppc|p\.p\.c\.?|crpc|cr\.?\s?p\.?\s?c\.?|peca)\b`,
  "gi",
);

// Where a neighbouring reference begins, e.g. "Section 302 and Article 10A".
const NEXT_REFERENCE =
  /(?<![A-Za-z])(?:sections?|sec\.|s\.|articles?|art\.|دفعہ|دفعات|سیکشن|آرٹیکل|شق)|\[\d/i;

function exists(law: LawId, number: string): boolean {
  return Boolean(catalog[law]?.[number]);
}

// Which law a nearby phrase names, if any.
function lawNamedIn(snippet: string): LawId | null {
  const lower = snippet.toLowerCase();
  for (const law of LAWS) {
    if (law.aliases.some((a) => lower.includes(a))) return law.id;
  }
  return null;
}

function resolve(
  unit: string,
  number: string,
  suffix: string | undefined,
  before: string,
  after: string,
): LegalReference[] {
  const candidates: string[] = suffix ? [`${number}${suffix.toUpperCase()}`, number] : [number];
  const isArticle = /^(art|آرٹیکل|شق)/i.test(unit);
  // English usually names the law after the number ("Section 154 of the CrPC"), Urdu often
  // before it ("تعزیراتِ پاکستان کی دفعہ 302"). Articles only exist in the Constitution.
  const urdu = /[؀-ۿ]/.test(unit);
  const named = isArticle
    ? null
    : urdu
      ? (lawNamedIn(before) ?? lawNamedIn(after))
      : (lawNamedIn(after) ?? lawNamedIn(before));
  const laws: LawId[] = named
    ? [named]
    : isArticle
      ? ["constitution"]
      : (["ppc", "crpc", "peca"] as LawId[]);
  for (const n of candidates) {
    const found = laws.filter((l) => exists(l, n)).map((law) => ({ law, number: n, known: true }));
    if (found.length) return found;
  }
  // Not in the knowledge base. Report it only when we know which law was meant.
  const law = named ?? (isArticle ? "constitution" : null);
  return law ? [{ law, number: candidates[0], known: false }] : [];
}

export function findReferenceMentions(input: string): ReferenceMention[] {
  const text = normalize(input);
  const mentions: ReferenceMention[] = [];

  for (const m of text.matchAll(UNIT_FIRST)) {
    // Look for the law name next to this reference only, not in a neighbouring one.
    const end = m.index + m[0].length;
    const after = text.slice(end, end + 45).split(NEXT_REFERENCE)[0];
    const before =
      text
        .slice(Math.max(0, m.index - 30), m.index)
        .split(NEXT_REFERENCE)
        .pop() ?? "";
    mentions.push({
      text: m[0],
      options: resolve(m[1], m[2], m[3] ?? m[4] ?? m[5], before, after),
    });
  }
  for (const m of text.matchAll(LAW_AFTER_NUMBER)) {
    mentions.push({
      text: m[0],
      options: resolve("section", m[1], m[2] ?? m[3] ?? m[4], "", m[5]),
    });
  }
  return mentions.filter((m) => m.options.length);
}

// Every provision the text refers to, without duplicates.
export function findReferences(input: string): LegalReference[] {
  const refs = findReferenceMentions(input).flatMap((m) => m.options);
  const seen = new Set<string>();
  return refs.filter((r) => {
    const key = `${r.law}:${r.number}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

export function chunkIdsFor(refs: LegalReference[]): string[] {
  return refs.filter((r) => r.known).flatMap((r) => catalog[r.law]?.[r.number]?.ids ?? []);
}
