/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TranslatorRouteImport } from './routes/translator'
import { Route as RightsRouteImport } from './routes/rights'
import { Route as NoticeRouteImport } from './routes/notice'
import { Route as FirRouteImport } from './routes/fir'
import { Route as ComplaintRouteImport } from './routes/complaint'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BailRouteImport } from './routes/bail'
import { Route as IndexRouteImport } from './routes/index'

const TranslatorRoute = TranslatorRouteImport.update({
  id: '/translator',
  path: '/translator',
  getParentRoute: () => rootRouteImport,
} as any)
const RightsRoute = RightsRouteImport.update({
  id: '/rights',
  path: '/rights',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticeRoute = NoticeRouteImport.update({
  id: '/notice',
  path: '/notice',
  getParentRoute: () => rootRouteImport,
} as any)
const FirRoute = FirRouteImport.update({
  id: '/fir',
  path: '/fir',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintRoute = ComplaintRouteImport.update({
  id: '/complaint',
  path: '/complaint',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BailRoute = BailRouteImport.update({
  id: '/bail',
  path: '/bail',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bail': typeof BailRoute
  '/chat': typeof ChatRoute
  '/complaint': typeof ComplaintRoute
  '/fir': typeof FirRoute
  '/notice': typeof NoticeRoute
  '/rights': typeof RightsRoute
  '/translator': typeof TranslatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bail': typeof BailRoute
  '/chat': typeof ChatRoute
  '/complaint': typeof ComplaintRoute
  '/fir': typeof FirRoute
  '/notice': typeof NoticeRoute
  '/rights': typeof RightsRoute
  '/translator': typeof TranslatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bail': typeof BailRoute
  '/chat': typeof ChatRoute
  '/complaint': typeof ComplaintRoute
  '/fir': typeof FirRoute
  '/notice': typeof NoticeRoute
  '/rights': typeof RightsRoute
  '/translator': typeof TranslatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bail'
    | '/chat'
    | '/complaint'
    | '/fir'
    | '/notice'
    | '/rights'
    | '/translator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bail'
    | '/chat'
    | '/complaint'
    | '/fir'
    | '/notice'
    | '/rights'
    | '/translator'
  id:
    | '__root__'
    | '/'
    | '/bail'
    | '/chat'
    | '/complaint'
    | '/fir'
    | '/notice'
    | '/rights'
    | '/translator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BailRoute: typeof BailRoute
  ChatRoute: typeof ChatRoute
  ComplaintRoute: typeof ComplaintRoute
  FirRoute: typeof FirRoute
  NoticeRoute: typeof NoticeRoute
  RightsRoute: typeof RightsRoute
  TranslatorRoute: typeof TranslatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/translator': {
      id: '/translator'
      path: '/translator'
      fullPath: '/translator'
      preLoaderRoute: typeof TranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rights': {
      id: '/rights'
      path: '/rights'
      fullPath: '/rights'
      preLoaderRoute: typeof RightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notice': {
      id: '/notice'
      path: '/notice'
      fullPath: '/notice'
      preLoaderRoute: typeof NoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fir': {
      id: '/fir'
      path: '/fir'
      fullPath: '/fir'
      preLoaderRoute: typeof FirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaint': {
      id: '/complaint'
      path: '/complaint'
      fullPath: '/complaint'
      preLoaderRoute: typeof ComplaintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bail': {
      id: '/bail'
      path: '/bail'
      fullPath: '/bail'
      preLoaderRoute: typeof BailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BailRoute: BailRoute,
  ChatRoute: ChatRoute,
  ComplaintRoute: ComplaintRoute,
  FirRoute: FirRoute,
  NoticeRoute: NoticeRoute,
  RightsRoute: RightsRoute,
  TranslatorRoute: TranslatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
