/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TranslatorRouteImport } from './routes/translator'
import { Route as LawRouteImport } from './routes/law'
import { Route as IncidentRouteImport } from './routes/incident'
import { Route as IndexRouteImport } from './routes/index'

const TranslatorRoute = TranslatorRouteImport.update({
  id: '/translator',
  path: '/translator',
  getParentRoute: () => rootRouteImport,
} as any)
const LawRoute = LawRouteImport.update({
  id: '/law',
  path: '/law',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentRoute = IncidentRouteImport.update({
  id: '/incident',
  path: '/incident',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/incident': typeof IncidentRoute
  '/law': typeof LawRoute
  '/translator': typeof TranslatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/incident': typeof IncidentRoute
  '/law': typeof LawRoute
  '/translator': typeof TranslatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/incident': typeof IncidentRoute
  '/law': typeof LawRoute
  '/translator': typeof TranslatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/incident' | '/law' | '/translator'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/incident' | '/law' | '/translator'
  id: '__root__' | '/' | '/incident' | '/law' | '/translator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IncidentRoute: typeof IncidentRoute
  LawRoute: typeof LawRoute
  TranslatorRoute: typeof TranslatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/translator': {
      id: '/translator'
      path: '/translator'
      fullPath: '/translator'
      preLoaderRoute: typeof TranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/law': {
      id: '/law'
      path: '/law'
      fullPath: '/law'
      preLoaderRoute: typeof LawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incident': {
      id: '/incident'
      path: '/incident'
      fullPath: '/incident'
      preLoaderRoute: typeof IncidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IncidentRoute: IncidentRoute,
  LawRoute: LawRoute,
  TranslatorRoute: TranslatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
